name: Museion Academy
favicon: null
layout_spectrum: 0.38461687113158405
typography_spectrum: 0.6688730388414115
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8142165215685964
  lightness: 0.37199804931879044
  saturation: 0.276153800310567
  rhythmicContrast: 0.15111670712940395
purpose: []
