name: Museion Academy
favicon: null
layout_spectrum: 0.38461687113158405
typography_spectrum: 0.6688730388414115
title: Museion Academy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.375
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.15111670712940395
purpose: []
